Improve compatibility: RxJS5, most.js, xstreams and maybe more
sindresorhus/observable-to-promise pull request #4
Opened 2017-03-03 13:16 UTC by shofel

## The Impetus
I've faced an issue in AVA [observable support](https://github.com/avajs/ava#observable-support). It works well with RxJS5 but doesn't work with [most](https://github.com/cujojs/most) and [xstream](https://github.com/staltz/xstream).

Partly the reason was in this lib: it relies on methods `.forEach()`, and `.then()`, which implemented not in all libraries. Using only `.subscribe` method appears more robust.

By the way, AVA and most/xstream still doesn't fixed for me. I've tested that by [`npm link`](https://docs.npmjs.com/cli/link)`.

## Tests
In this PR I've also refactored the tests to make it really easy to add more observable libraries under test. Although we may not need this when relying on just the `.subscribe()` method that is very basic and crucial for any implementation of observable.

2017-03-03 16:32 UTC, sindresorhus commented
> By the way, AVA and most/xstream still doesn't fixed for me.

Might be caused by the observable check: https://github.com/avajs/ava/blob/157ef25aff0bae7145a6133928d2bdd0da853a78/lib/test.js#L75

2017-03-03 16:32 UTC, sindresorhus requested changes

2017-03-03 16:32 UTC, sindresorhus commented on index.js
> +			});
This doesn't seem to handle the Observable erroring.

2017-03-03 16:47 UTC, shofel commented
> Might be caused by the observable check:
> https://github.com/avajs/ava/blob/157ef25aff0bae7145a6133928d2bdd0da853a78/lib/test.js#L75

Yeah, I've checked this and this is true. But for some reason [the same check](https://github.com/sindresorhus/observable-to-promise/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcL6) passes in tests for this package.

2017-03-03 16:54 UTC, shofel commented
I also should add the tests for handling errors.

2017-03-03 17:58 UTC, sindresorhus commented
@benlesh Does this change look ok to you?

2017-03-04 14:31 UTC, shofel commented
Added tests for handling errors

2017-03-14 13:09 UTC, sindresorhus approved these changes

2017-03-14 13:09 UTC, merged

2017-03-14 13:30 UTC, shofel commented
:ghost: ￼￼￼￼￼￼￼￼￼￼￼￼